# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci package.
sudo: required
dist: trusty
services:
  - docker

language: generic
compiler:
  - gcc
cache: ccache

notifications:
  email:
    recipients:
      - rhaschke@techfak.uni-bielefeld.de
      - me@v4hn.de
env:
  matrix:
    - ROS_DISTRO=kinetic  ROS_REPO=ros
    - ROS_DISTRO=kinetic  ROS_REPO=ros-shadow-fixed

before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git .moveit_ci
  - . .prepare_overlay.sh

script:
  - source .moveit_ci/travis.sh
